project:
  type: website

website:
  title: "nikhita_website_quarto"
  navbar:
    left:
      - href: index.html
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

