project:
  type: website
  output-dir: docs

website:
  title: "nikhita_website_quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: https://www.linkedin.com/in/nikhita-damaraju/
      - text: "{{< iconify fa6-brands twitter >}}"
        href: https://twitter.com/NikhitaDamaraju
      - text: "{{< iconify fa6-brands github >}}"
        href: http://github.com/nikhita-damaraju/
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=IYzv-hgAAAAJ&hl=en
      - text: CV
        href: ./Nikhita_Damaraju_CV_2021.pdf
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

