project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    search: false
    pinned: true
    fontsize: 1.8em
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: talks.qmd
        text: Talks
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog
    
    right: 
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: https://www.linkedin.com/in/nikhita-damaraju/
      - text: "{{< iconify fa6-brands twitter >}}"
        href: https://twitter.com/NikhitaDamaraju
      - text: "{{< iconify fa6-brands github >}}"
        href: http://github.com/nikhita-damaraju/
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=IYzv-hgAAAAJ&hl=en
      - text: CV
        href: ./Nikhita_Damaraju_CV_2023.pdf
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

