---
title: 
---


# Major experiences
### Columbia University Herbert Irving Center for Cancer Research
Data Science Scholars Program 2020
<br> November 2020 - present

* Created a UNIX and R-based analysis pipeline consisting of copy number variant prediction algorithms on whole exome sequencing datasets for cancer patients.
* Created a user friendly IDE using AWS Cloud9 to set up the entire pipeline that can be used on human and mouse samples to analyse differences in healthy vs tumor datasets.

### Inflammatix inc., Burlingame, CA
Computational Biology intern 
<br> May 2021 - September 2021

* Implemented a multi-cohort analysis framework on 20 publicly available datasets consisting of a heterogenous set of >2000 samples.

* Derived a gene expression signature to distinguish between healthy controls and Systemic Lupus Erythematosus (SLE), validated in an independent set with high accuracy.

### Dual Degree (B.S. - M.S.) Thesis 
Systems Genetics Lab, Robert Bosch Center for Data Science and AI, IBSE
<br> July, 2019 – May, 2020
<br> Thesis advisor: Dr. Himanshu Sinha	

 <u> Background: </u>

Preterm Birth is one of the leading causes of death in infants in India that requires accurate and population specific estimation of gestational age. As a part of this project, birth outcomes for a cohort of 7000 pregnant women in North India (GARBH-Ini cohort) were analyzed. This project was implemented in close collaboration with a team of clinicians at the <a href = "https://thsti.res.in/newthsti/"> Translational Health Sciences Institute, Faridabad </a> as a part of Bill and Melinda Gates foundation grant, Grand Challenges of India grant and BIRAC grant.

<u> Key Findings: </u> 

* Implemented feature selection to build a regression model that predicts gestational age (GA) in the first trimester.
* Used machine learning algorithms such as random forest and XGBoost for GA estimation in second and third trimesters with highest preterm labelling accuracy when compared to all other models.
* Assessed multiple gestational age (GA) estimation models with statistical methods such as Bland-Altman analysis to find differences in prediction between developed and existing models.

<u> Achievements: </u>

* Published key findings in the form of 2 articles that are published and submitted to peer-reviewed journals such as BMC Pregnancy and Childbirth.
* Presented research at multiple Data Science and AI academic conferences winning accolades such as Best Presentation at the IBSE 4th annual workshop.

### Stanford University CA
Summer Intern, Department of Biochemistry	
May – August, 2019
<br>Advisor: Dr. Julia Salzman

*	Designed a pipeline from scratch that implements generalized linear modelling to identify conserved features that facilitate alternative splicing in primates. 
*	Correlated genomic and transcriptomic using the <a href = "http://www.nhprtr.org"> NHPRTR dataset </a> to identify genomic repeat-based features conserved across 6 primates. 
*	Identified conserved SINE and LINE repeat-based features that are significantly correlated to the formation of alternately spliced transcripts.

### Khorana summer fellowship, Stanford University CA
May – August, 2018
<br>Advisor: Dr. Julia Salzman

*	Selected as one of the 40 (out of 1000 applicants) Khorana fellowship grant recipients funding summer research projects  
*	Designed a bioinformatic pipeline for downstream analysis of Epstein Barr virus infected human B-cell transcriptomic datasets downloaded from SRA for lytic and latent infection stages of the virus.
*	Characterized the presence of circRNAs and alternative splicing present in LMP-2A and LMP-2B genes in Epstein-Barr virus validating previous experimental results.
*	Summarized research in the form a detailed report to be presented at the department research seminar.

### Tata Institute of Fundamental Research, Mumbai
May – August, 2017
<br>Advisor: Dr. Mithilesh Mishra

* Treated fission yeast cells (S. pombe) with different classes of Histone Deacetylase inhibitors like Trichostatin A and Nicotinamide that are commonly used in the treatment of cancers.
* Observed and reported defects in primitive cell wall (septum) formation 
<br>
<br>

# Course projects

* 