---
title: 
output: 
  html_document:
    toc: true
    toc_float: true
---

# Publications
(<sup>1</sup> joint first authors)

### 2021
* Damaraju, Nikhita<sup>1</sup>, Ashley Xavier<sup>1</sup>, Ramya Vijayram, Bapu Koundinya Desiraju, Sumit Misra, Ashok Khurana, Nitya Wadhwa, et al. “Development of Second and Third-Trimester Population-Specific Machine Learning Pregnancy Dating Model (Garbhini-GA2) Derived from the GARBH-Ini Cohort in North India,” October 4, 2021. <a href = "https://doi.org/10.1101/2021.10.02.21264450"> medRxiv article </a>

*	Vijayram R<sup>1</sup>, *Damaraju N*<sup>1</sup>, Xavier A<sup>1</sup>, Desiraju BK, Thiruvengadam R, Misra S, et al. Comparison of first trimester dating methods for gestational age estimation and their implication on preterm birth classification in a North Indian cohort. BMC Pregnancy and Childbirth. 2021 Apr 30;21(1):343. <a href = "https://bmcpregnancychildbirth.biomedcentral.com/articles/10.1186/s12884-021-03807-4"> BMC article </a>

### 2019

*	B P Kailash<sup>1</sup>, D Karthik<sup>1</sup>, Mousami Shinde<sup>1</sup>, Nikhita Damaraju<sup>1</sup>, et al., ”ChassiDex: A microbial database useful for synthetic biology applications”, submitted on July 16th, 2019, bioRxiv 703033 <a href = "https://www.biorxiv.org/content/biorxiv/early/2019/07/16/703033.full.pdf"> bioRxiv article </a>


# Blog/Newsletter articles

* Ashley Xavier, Himanshu Sinha, Nikhita Damaraju, "Developing India-specific pregnancy dating model from Garbhini cohort", AI for Social Good, Feb 9, 2021, Robert Bosch Centre for Data Science and AI (RBCDSAI) <a href = "https://rbcdsai.iitm.ac.in/blogs/garbhini/"> article </a>

* I discussed my experience being awarded the Khorana Summer Fellowship 2018 for an internship at Stanford University in their Summer Blog 2018 edition <a href = "https://www.winstepforward.org/blog/2018/09/nikhita-damaraju-summer-blog-2018/"> article </a>

*	I wrote about a science communication initiative that I led as a part of the International Genetically Engineered Machine (iGEM) Competition called "Language Project", submitted to IEEE India Info. Vol 13 No. 3 for the Jul-Sep 2018 Newsletter, p67-p68 <a href = "https://site.ieee.org/indiacouncil/files/2018/11/p67-p68.pdf"> IEEE article </a>

* Immerse is a scientific magazine of Indian Institute of Technology, Madras. As one of the writers for the 2018 issue, I wrote an article breaking down research conducted at The Uncertainty Lab, IIT Madras in <a href = "https://www.t5eiitm.org/unraveling-uncertainty/"> article </a>
