---
title: 
output: 
  html_document:
    toc: true
    toc_float: true
---

# Conferences

* Initiative for Biological Systems Engineering 8th workshop (2021)
* 7th RBCDSAI workshop on recent progress in Data Science and AI (2020) <a href = "https://www.youtube.com/watch?v=P0UkA8wCyLg&t=1s"> video presentation </a>
* India EMBO symposium on Synthetic Biology (2020)
* First position, Initiative for Biological Systems Engineering 5th workshop, IIT Madras (2019)
* IITM-THSTI conclave: Transforming Maternal and Child Health through Data Science (2019)
* First position, Research Poster Presentation competition, Tata Consultancy Services, Shaastra (2019)
* Gold medal, Foundational Advance track (International Genetically Engineered Machine) iGEM competition, Boston (2018)
* Silver medal, Software track, iGEM competition, Boston (2017)
* Selected for Harvard Project for Asian and International Relations under Health and Social policy track (2018)
* Among top 40 (semifinalists) of 600 teams at Carbon zero Energy Challenge for energy efficient solutions (2017)
* Silver medal, Measurement track, iGEM competition, Boston (2016)

# Posters

* India EMBO symposium on Synthetic Biology (2020)
* Robert Bosch Center for Data Science and AI inauguration, IIT Madras (2019)
* Initiative for Biological Systems Engineering (IBSE) colloquium (2019)
* Research Poster Presentation competition, Tata Consultancy Services, Shaastra (2019)
* Foundational Advance track: (International Genetically Engineered Machine) iGEM competition, Boston (2018)
* Software track: iGEM competition, Boston (2017)
* Measurement track: iGEM competition, Boston (2016)