---
title: 
output: 
  html_document:
    toc: true
    toc_float: true
---
# 2021
### Graduate Teaching Assistant, Probability (P8104)
Instructor: Dr. Xiaoyu Che
<u> <br> September 2021 – December 2021 </u>

* Conceptualized questions for weekly assignments 
* Held office hours to clarify theoretical concepts
* Grading weekly homework and examinations for 170 students

### Graduate Teaching Assistant, Data Science (P8105)
Instructor: Dr. Jeff Goldsmith
<u> <br> September 2021 – December 2021 </u>

* Graded weekly homework assignments
* Mentored student groups for the final project
* Held weekly office hour sessions involving debugging and explaining key tidyverse/dplyr functions to 180 students


# 2020
### Graduate Teaching Assistant, Quantitative and Population Genetics 
Instructor: Dr. Himanshu Sinha
<u> <br> January 2020 - June 2020 </u>

* Conducted online end final examinations in a virtual setting
* Graded quizzes for 20 students 
* Solved conceptual doubts for students during office hours

# 2019
### Graduate Teaching Assistant, Current topics in synthetic biology 
Instructor: Dr. Karthik Raman
<u> <br> July 2019 – December 2019 </u> 

Assessed the performance for 15 students in 3 sets of comprehensive research seminars that covered different aspects of Synthetic Biology.

