---
title: "Reviewing the Public Health Genetic Landscape of Polycystic Ovarian Syndrome"
categories: ["Public_health","Medical_Genetics", "ELSI_health_services"]
year: 2024
---

This literature review report was done as a part of PHG 513: Pharmacogenomics and Toxicogenomics in Winter 2024 at University of Washington.

### Motivation

The etiology of PCOS is based on the intricate interactions between multiple genetic and environmental factors. PCOS highlights the vital need for a thorough understanding in order to provide tailored therapies and successful interventions. The complex interactions between insulin resistance, hyperandrogenism, and hormone dysregulation affect metabolic and reproductive processes, contributing to the wide range of clinical manifestations of this illness. The intricacy of PCOS and its effects on the world's female population are highlighted by the inclusion of environmental factors and the intricate interplay between genetic and environmental aspects. By addressing this complexity, we can improve the quality of life for individuals impacted by this complex endocrine condition and open the door to more focused and successful therapy approaches across different socio-environmental settings worldwide

### Topics analyzed

1.  Diagnosis, fundamental biology and genetic factors
2.  Global epidemiology of PCOS
3.  Environmental and lifestyle-based factors
4.  Ethical, Legal and Social Implications of PCOS
