---
title: "Using social media as a lens to understand caregiver perspectives and barriers to care for pediatric rare genetic disorders"
categories: ["Public_Health","ELSI_health_services"]
year: 2024
---

This project was done as a part of GH 539: Analyzing Qualitative Data in Winter 2024 at University of Washington.

### Motivation

According to the Orphan Drug Act, fewer than 200,000 people in the United States suffer from a rare disease, and about 400 million people worldwide face rare diseases. The complexity comes from the fact that 95% of these conditions have no FDA-approved treatment and 65% are associated with reduced life expectancy and quality of life. The frequency of rare diseases, especially genetic diseases, in children under 5 years old is increasing every year. Seeking a diagnosis can be emotionally and financially taxing, with the added risk of getting a misdiagnosis of common conditions. 

Social media plays a vital role in providing a wider reach and connecting parents facing these challenges and provides a platform of support. An active rare disease community on social media offers a unique opportunity for research that provides insights that help understand these diseases and enable treatment options. The utilization of social media platforms, particularly Facebook and Instagram, by parents of children with rare genetic disorders is a phenomenon that has received attention in existing literature. Specifically in situations where offline support groups for specific rare disorders are unavailable, social media serves as an important tool that offers a sense of community, understanding, and sharing experiences.

### Aims

1.  Identifying patterns and trends in social media engagement among parents and caregivers,
2.  Exploring implications of social media usage in different aspects of pediatric rare genetic disorders such as diagnosis, treatment, health insurance, etc.

### Methods

1.  Codebook development to analyze data from published news articles of caregivers and research studies.
2.  Identifying social science theoretical frameworks suitable for analyzing the aims of the project.
3.  Thematic analysis to identify key patterns to answer the question of interest.
